spring:
  config:
    activate:
      on-profile: local
  datasource:
    hikari:
      username: dongju
      password: dbsdk93!
#            jdbc-url: jdbc:mysql://host.docker.internal:3306/fake_book
      jdbc-url: jdbc:mysql://localhost:3306/fake_book
      driver-class-name: com.mysql.cj.jdbc.Driver